# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20180524_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_date_to',
            field=models.DateField(),
        ),
    ]
